services:
  react-app:
    restart: always
    build: ../awesomereactapp
    ports:
      - "5000:80"
    networks:
      - awesome-app

  hapi-app:
    build: ../hapijs
    container_name: hapi_container
    ports:
      - "4000:3000"
    networks:
      - awesome-app
    depends_on:
      - mongo-app
    links:
      - mongo-app

  mongo-app:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      - awesome-app
    volumes:
      - ./data:/data/db

networks:
  awesome-app:
    driver: bridge

